name: TruffleHog Scan

on:
  push:
    branches:
      - main  # Change this to the branch you want to monitor.

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run TruffleHog Scan
      uses: edplato/trufflehog-actions-scan@master
