name: TruffleHog Scan

on:
  push:
    branches:
      - main  # Change this to the branch you want to monitor.
  pull_request:


jobs: 
  TruffleHog: 
    runs-on: ubuntu-latest 

    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3 
        with: 
          fetch-depth: 0

      - name: Run TruffleHog Scan
        uses: edplato/trufflehog-actions-scan@master
